### ISSUE TITLE
Turn off ads

### ISSUE THREAD

**Issue by daguar** [lippytak/ebt-near-me#112]
This was decided to capture rate of usage by county partners in a clean way.

**Comment by alanjosephwilliams** [comment]
Not until #66

**Comment by lippytak** [comment]
All ads paused. Quick summary:
![overall](https://cloud.githubusercontent.com/assets/2533112/6008388/03bb9ad0-aad6-11e4-8b5e-5d0095ef4d0f.png)

ATM keyword view:
![atm](https://cloud.githubusercontent.com/assets/2533112/6008399/05bc667a-aad6-11e4-845a-097daae1e35b.png)

Stores keyword view:
![atm](https://cloud.githubusercontent.com/assets/2533112/6008402/09acc342-aad6-11e4-9865-75c7a91ae180.png)

ATM ads are pretty low volume but look like they're performing really well...
