### ISSUE TITLE
Status check on pilot

### ISSUE THREAD

**Issue by daguar** [lippytak/ebt-near-me#116]

**Comment by daguar** [comment]
Jake, assigning this to you for now but this is basically just to check in on how the EBTnearMe pilot is going.

**Comment by lippytak** [comment]
Just checked. Nobody knows current status. Angela will check with counties and I'll forward along anything she learns.

Closing this issue but now this becomes relevant: https://github.com/lippytak/ebt-near-me/issues/117

**Comment by alanjosephwilliams** [comment]
woof

On Mon, Jan 26, 2015 at 11:30 AM, Jake Solomon <notifications@github.com>
wrote:

> Closed #116 <https://github.com/lippytak/ebt-near-me/issues/116>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lippytak/ebt-near-me/issues/116#event-224860430>.
>



-- 
t:  @alanjosephwilli
p: 817 713 6264
