### ISSUE TITLE
Setup ethnio survey

### ISSUE THREAD

**Issue by lippytak** [lippytak/ebt-near-me#66]
stub

**Comment by alanjosephwilliams** [comment]
*first screen*
### Have one Minute?
#### You'll earn $5 at Amazon.com.

We are looking for a few visitors to answer three brief questions. It takes only a minute, and you'll receive a $5 Amazon gift code in return. 

Your feedback will help us improve EBTNearMe.org!

---------------

*second screen*

1. So, what are you looking for today?
- [ ] Retail stores accepting CalFresh/EBT 
- [ ] Restaurants accepting CalFresh/EBT 
- [ ] Farmers' Markets 
- [ ] No-fee ATMs accepting EBT 
- [ ] Something else (tell us!) (*opens an input form*)

2. How often are you looking for stores or restaurants accepting CalFresh?
- [ ] All the time 
- [ ] Somewhat often 
- [ ] Not often 
- [ ] Never 

3. What's are the most difficult or frustrating parts of using your benefits?
- [ ] Finding stores and restaurants accepting benefits 
- [ ] Knowing what I can purchase with benefits 
- [ ] Travel to and from places accepting benefits 
- [ ] Budgeting the use of my benefits 
- [ ] Staying enrolled in my benefits programs 
- [ ] Other things (tell us!) (*opens input form*)

4. Share your e-mail address or cell phone number— We'll send you a $5 Amazon gift code to say thanks for your time!

----------------

#### Thank you for your time!
