### ISSUE TITLE
Run in-app user survey

### ISSUE THREAD

**Issue by lippytak** [lippytak/ebt-near-me#80]
Let’s design a 1-3 question survey for active EBTNearMe users. At the very least I’d like to know:
- What were you looking for?
- Did you find it?
- How could we make this better?

See https://github.com/lippytak/ebt-near-me/issues/71 for context.

**Comment by lippytak** [comment]
Donezo, right? @alanjosephwilliams could you link to the results here and close this?

**Comment by alanjosephwilliams** [comment]
Results are still pending an e-mail follow up—let's close when we have
those.

AJW

On Mon, Jan 26, 2015 at 8:11 AM, Jake Solomon <notifications@github.com>
wrote:

> Donezo, right? @alanjosephwilliams <https://github.com/alanjosephwilliams>
> could you link to the results here and close this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lippytak/ebt-near-me/issues/80#issuecomment-71485879>.
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by lippytak** [comment]
https://github.com/codeforamerica/health/wiki/Research:-January-2015-User-Research#ebtnm
